### ISSUE TITLE
How show from on front page

### ISSUE THREAD

**Issue by kreker92** [refinery/refinerycms-forms#6]
I've installed this plugin after site was ready. So I didnt find any documentation how to show the form on front page.

**Comment by bricesanchez** [comment]
@kreker92 This extension was developped in order to generate form extensions. It should be used by CLI only and after that you will be able to access to your extension and add it as an homepage

**Comment by kreker92** [comment]
I've already created the from from CLI. So the question is: How can I get access to this extension and add it as an homepage.

**Comment by kreker92** [comment]
So I cant insert it like a part of page by standart instructions?
Thank you for so fast answer!

**Comment by bricesanchez** [comment]
At this time there is no feature like `refinerycms_page_images` or `refinerycms_pages_resources` to be able to attach a form to pages, it will be a nice feature.

So at this time, you will have to use the generated form page as your homepage

**Comment by kreker92** [comment]
Thanks for explanation!
